name: crazy_food
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.0.0
  carousel_slider: ^4.0.0
  pin_code_text_field: ^1.7.1
  get_storage: ^2.0.3
  image_picker: ^0.8.4+7
  dio: ^4.0.4
  get: ^4.6.1
  photo_view: ^0.13.0
  sliding_sheet: ^0.5.0
  fluttertoast: ^8.0.8
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.10
  cached_network_image: ^3.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_ringtone_player: ^3.1.1
  badges: ^2.0.1
  firebase_dynamic_links: ^4.0.0
  percent_indicator: ^3.4.0
  introduction_screen: ^2.1.0
  flutter_rating_bar: ^4.0.0
  dropdown_search: ^2.0.1
  lazy_load_scrollview: ^1.3.0
  toggle_switch: ^1.4.0
  fcm_config: ^3.3.4
  shimmer: ^2.0.0
  lottie: ^1.2.1
  connectivity_plus: ^2.0.2
  flutter_native_splash: ^2.1.3+1
  sliver_tools: ^0.2.5
  flutter_shimmer: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

#  flutter pub run flutter_launcher_icons:main


  flutter_lints: ^1.0.0


flutter_native_splash:
#  color: "#FFFFFF"
  image: assets/images/icon.png
  background_image: "assets/images/back.png"
  android: true
  ios: true
  remove_alpha_ios: true
  #  android_gravity: fill
  #  ios_content_mode: scaleAspectFill

  # run this command
  #  flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/json/
